<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

In [32]:
arr = np.arange(200,400)
arr

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38

In [33]:
arr_new = arr[50:100]
arr_new = np.copy(arr_new)
print(arr_new)

[250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285
 286 287 288 289 290 291 292 293 294 295 296 297 298 299]


In [34]:
arr = np.arange(80,100)
arr_copy = arr.copy()
arr_copy=arr_copy[0:20]
arr_copy[:]=55
arr_copy

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55])

In [35]:
print(id(arr))

139976078681552


In [41]:
xyz = np.arange(1,31)
xyz=xyz.reshape(5,6)
xyz

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [43]:
print(xyz[:,[5,2]]) #extracting any desired column with respect to Index Position Number

[[ 6  3]
 [12  9]
 [18 15]
 [24 21]
 [30 27]]


In [37]:
xyz[[1,2,3,4],[4,3,2,7]]

array([15, 24, 33, 48])

In [38]:
arr = np.arange(500,600).reshape(10,10)
arr

array([[500, 501, 502, 503, 504, 505, 506, 507, 508, 509],
       [510, 511, 512, 513, 514, 515, 516, 517, 518, 519],
       [520, 521, 522, 523, 524, 525, 526, 527, 528, 529],
       [530, 531, 532, 533, 534, 535, 536, 537, 538, 539],
       [540, 541, 542, 543, 544, 545, 546, 547, 548, 549],
       [550, 551, 552, 553, 554, 555, 556, 557, 558, 559],
       [560, 561, 562, 563, 564, 565, 566, 567, 568, 569],
       [570, 571, 572, 573, 574, 575, 576, 577, 578, 579],
       [580, 581, 582, 583, 584, 585, 586, 587, 588, 589],
       [590, 591, 592, 593, 594, 595, 596, 597, 598, 599]])

In [39]:
arr[[3,6,6,1,2,5,8,7,0,9],[4,7,0,0,7,9,6,0,5,7]]

array([534, 567, 560, 510, 527, 559, 586, 570, 505, 597])

In [40]:
np.arange(100,180).reshape(20,4)

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 137, 138, 139],
       [140, 141, 142, 143],
       [144, 145, 146, 147],
       [148, 149, 150, 151],
       [152, 153, 154, 155],
       [156, 157, 158, 159],
       [160, 161, 162, 163],
       [164, 165, 166, 167],
       [168, 169, 170, 171],
       [172, 173, 174, 175],
       [176, 177, 178, 179]])

In [44]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

# Operations

In [52]:
ar = np.arange(0,11)
ar1 = np.arange(0,11)
ar2 = np.arange(1,101)

print(ar)
print(ar1)
print(ar2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [53]:
len(ar) + len(ar1)

22

In [60]:
ar * ar1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
ar + ar1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
ar - ar1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
ar/ar1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Universal Array Functions

In [72]:
print(np.sqrt(ar), '\n')
print(np.exp(ar), '\n')
print(np.log(ar), '\n')
print(np.mean(ar), '\n')
print(np.median(ar), '\n')
print(np.std(ar), '\n')
print(np.var(ar), '\n')
print(np.max(ar), '\n')

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04] 

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509] 

5.0 

5.0 

3.1622776601683795 

10.0 

10 



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
