<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(200,400)
arr

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38

In [3]:
arr_new = arr[50:100]
arr_new = np.copy(arr_new)
print(arr_new)

[250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285
 286 287 288 289 290 291 292 293 294 295 296 297 298 299]


In [4]:
arr = np.arange(80,100)
arr_copy = arr.copy()
arr_copy=arr_copy[0:20]
arr_copy[:]=55
arr_copy

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55])

In [5]:
print(id(arr))

139976079658880


In [10]:
xyz = np.arange(1,51)
xyz=xyz.reshape(5,10)
xyz

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [12]:
xyz[[1,2,3,4],[4,3,2,7]]

array([15, 24, 33, 48])

In [13]:
arr = np.arange(500,600).reshape(10,10)
arr

array([[500, 501, 502, 503, 504, 505, 506, 507, 508, 509],
       [510, 511, 512, 513, 514, 515, 516, 517, 518, 519],
       [520, 521, 522, 523, 524, 525, 526, 527, 528, 529],
       [530, 531, 532, 533, 534, 535, 536, 537, 538, 539],
       [540, 541, 542, 543, 544, 545, 546, 547, 548, 549],
       [550, 551, 552, 553, 554, 555, 556, 557, 558, 559],
       [560, 561, 562, 563, 564, 565, 566, 567, 568, 569],
       [570, 571, 572, 573, 574, 575, 576, 577, 578, 579],
       [580, 581, 582, 583, 584, 585, 586, 587, 588, 589],
       [590, 591, 592, 593, 594, 595, 596, 597, 598, 599]])

In [23]:
arr[[3,6,6,1,2,5,8,7,0,9],[4,7,0,0,7,9,6,0,5,7]]

array([534, 567, 560, 510, 527, 559, 586, 570, 505, 597])

In [30]:
np.arange(100,180).reshape(20,4)

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 137, 138, 139],
       [140, 141, 142, 143],
       [144, 145, 146, 147],
       [148, 149, 150, 151],
       [152, 153, 154, 155],
       [156, 157, 158, 159],
       [160, 161, 162, 163],
       [164, 165, 166, 167],
       [168, 169, 170, 171],
       [172, 173, 174, 175],
       [176, 177, 178, 179]])