<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1.dtype

dtype('int64')

In [4]:
arr2 = np.array([[2,3,4],[2,4,5]])
arr2

array([[2, 3, 4],
       [2, 4, 5]])

In [5]:
arr2.shape

(2, 3)

In [6]:
# return evenly spaced value
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# return array with 2nd number stepping
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((2,3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
print(np.identity(2, dtype=int))
# or
print(np.eye(2,3, dtype=int))

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]]


In [11]:
np.random.rand(2,3) #return random number array

array([[0.05917258, 0.42768589, 0.48725911],
       [0.6020157 , 0.29469917, 0.82914587]])

In [12]:
#return 2 array of 3 rows and 2 columns
np.random.rand(2,3,2)

array([[[0.48589927, 0.03210089],
        [0.58976668, 0.47553112],
        [0.45398134, 0.28590005]],

       [[0.63182057, 0.20724442],
        [0.66869831, 0.50920322],
        [0.3785205 , 0.87468951]]])

In [13]:
#returns a random between 2 and 3000
np.random.randint(2,3000)

271

In [14]:
#returns 2 array of 4 different numbers
np.random.randint(10,100,size=(1,2))

array([[18, 34]])

In [15]:
#return an array of different numbers
np.random.randint(1,10,4)

array([7, 2, 9, 1])

In [16]:
#return an array of 4 diiferent random numbers and of shape(2,2)
np.random.randint(1,20,4).reshape(2,2)

array([[11, 12],
       [13, 19]])

# Lecture 29 - 09 - 2020


# min,max,argmax,argmin

In [31]:
ran = np.random.randint(10,20, 8).reshape(2,4)
print(ran)
print(ran.max())
print(ran.min())
print(ran.argmax()) #provide index of maximum number
print(ran.argmin()) #provide index of minimum 

[[13 17 18 15]
 [17 16 16 13]]
18
13
2
0


<attribute 'dtype' of 'numpy.ndarray' objects>