<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1.dtype

dtype('int64')

In [4]:
arr2 = np.array([[2,3,4],[2,4,5]])
arr2

array([[2, 3, 4],
       [2, 4, 5]])

In [5]:
arr2.shape

(2, 3)

In [7]:
# return evenly spaced value
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# return array with 2nd number stepping
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((2,3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
print(np.identity(2, dtype=int))
# or
print(np.eye(2,3, dtype=int))

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]]
