<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays

In [32]:
import numpy as np

In [33]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [34]:
arr1.dtype

dtype('int64')

In [35]:
arr2 = np.array([[2,3,4],[2,4,5]])
arr2

array([[2, 3, 4],
       [2, 4, 5]])

In [36]:
arr2.shape

(2, 3)

In [37]:
# return evenly spaced value
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# return array with 2nd number stepping
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [39]:
np.zeros((2,3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0]])

In [40]:
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
print(np.identity(2, dtype=int))
# or
print(np.eye(2,3, dtype=int))

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]]


In [42]:
np.random.rand(2,3) #return random number array

array([[0.8533379 , 0.0595091 , 0.8414638 ],
       [0.08515791, 0.4386745 , 0.48850934]])

In [43]:
#return 2 array of 3 rows and 2 columns
np.random.rand(2,3,2)

array([[[0.49305653, 0.20005006],
        [0.01635122, 0.60404651],
        [0.76519184, 0.34191444]],

       [[0.8026679 , 0.62391803],
        [0.68314021, 0.2675897 ],
        [0.77679616, 0.93895634]]])

In [44]:
#returns a random between 2 and 3000
np.random.randint(2,3000)

1084

In [45]:
#returns 2 array of 4 different numbers
np.random.randint(10,100,size=(1,2))

array([[57, 95]])

In [46]:
#return an array of different numbers
np.random.randint(1,10,4)

array([5, 1, 5, 6])

In [47]:
#return an array of 4 diiferent random numbers and of shape(2,2)
np.random.randint(1,20,4).reshape(2,2)

array([[14,  5],
       [ 8,  9]])

# Lecture 29 - 09 - 2020


### min,max,argmax,argmin

In [48]:
ran = np.random.randint(10,20, 8).reshape(2,4)
print(ran)
print(ran.max())
print(ran.min())
print(ran.argmax()) #provide index of maximum number
print(ran.argmin()) #provide index of minimum 

[[17 12 15 11]
 [14 19 19 17]]
19
11
5
3


### Indexing


In [49]:
arr = np.arange(50,150)
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [67]:
print(arr[5])
print(arr[17])
print(arr[34])
print(arr[28])
print(arr[48])
print(arr[61])
print(arr[89])
print(arr[96])
print(arr[68])
print(arr[99])

55
67
84
78
98
111
139
146
118
149


In [70]:
print(arr[58:83])#108:132
print(arr[22:66])#72:115

[108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132]
[ 72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115]
