<a href="https://colab.research.google.com/github/shubhkhanna/Colab-Notebooks-IB241/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays

In [30]:
import numpy as np

In [31]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [32]:
arr1.dtype

dtype('int64')

In [33]:
arr2 = np.array([[2,3,4],[2,4,5]])
arr2

array([[2, 3, 4],
       [2, 4, 5]])

In [34]:
arr2.shape

(2, 3)

In [35]:
# return evenly spaced value
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# return array with 2nd number stepping
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [37]:
np.zeros((2,3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
np.ones((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
print(np.identity(2, dtype=int))
# or
print(np.eye(2,3, dtype=int))

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]]


In [40]:
np.random.rand(2,3) #return random number array

array([[0.56512031, 0.1057265 , 0.28730286],
       [0.99509577, 0.35186002, 0.9779123 ]])

In [41]:
#return 2 array of 3 rows and 2 columns
np.random.rand(2,3,2)

array([[[0.99469114, 0.52820158],
        [0.88531381, 0.62529355],
        [0.08259665, 0.11779141]],

       [[0.37756284, 0.75995403],
        [0.77508492, 0.20336047],
        [0.22573933, 0.33854457]]])

In [42]:
#returns a random between 2 and 3000
np.random.randint(2,3000)

1502

In [43]:
#returns 2 array of 4 different numbers
np.random.randint(10,100,size=(1,2))

array([[60, 55]])

In [44]:
#return an array of different numbers
np.random.randint(1,10,4)

array([1, 3, 4, 1])

In [45]:
#return an array of 4 diiferent random numbers and of shape(2,2)
np.random.randint(1,20,4).reshape(2,2)

array([[ 8, 16],
       [ 3, 10]])